baseURL = "http://example.org/"
languageCode = "en-us"
theme = "apsho-hugo-theme"
title = "Apsho | App landing template"
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 3
[[menu.main]]
name = "Services"
url = "#faq"
weight = 4
[[menu.main]]
name = "About"
url = "#feature"
weight = 2
[[menu.main]]
name = "Home"
url = "#hero"
weight = 1
[[menu.sitemap]]
name = "Contact"
url = "/contact"
weight = 4
[[menu.sitemap]]
name = "Privacy & Policy"
url = "/privacy"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "/blog"
weight = 2
[[menu.sitemap]]
name = "Home"
url = "#"
weight = 1
[params]
copyright1 = "All right reserved"
copyright2 = "Copyright © Apsho 2020"
email = "help@staticmania.com"
footerTitle = "Get the latest app updates"
formspreeURL = "https://formspree.io/mjvankow"
googleAnalytics = "UA-175025671-2"
logo = "images/logo.png"
[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "apsho@example.com"
phone = "+(448) 833 5272 332"
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
github = "https://github.com/StaticMania"
twitter = "https://twitter.com/static_mania"
